const FIRST_NAMES = [
  "Ziggy",
  "Nova",
  "Quill",
  "Sable",
  "Axel",
  "Moxie",
  "Pip",
  "Nyx",
  "Rogue",
  "Orbit",
  "Blip",
  "Vex",
  "Jinx",
  "Echo",
  "Pixel",
  "Rune",
  "Comet",
  "Holo",
  "Gizmo",
  "Fuzz",
  "Bramble",
  "Kite",
  "Pogo",
  "Lumen",
  "Sprocket",
  "Doodle",
  "Quasar",
  "Nimbus",
  "Bop",
  "Zazu",
  "Tango",
  "Wisp",
  "Zebra",
  "Taffy",
  "Glimmer",
  "Marble",
  "Rocket",
  "Flint",
  "Sprout",
  "Velvet",
  "Thimble",
  "Skipper",
  "Bolt",
  "Pickle",
  "Yodel",
  "Mango",
  "Fable",
  "Biscuit",
  "Jazz",
  "Drift",
];

const LAST_NAMES = [
  "Moonpickle",
  "Stormbucket",
  "Cloudwhisk",
  "Glitterfax",
  "Bumbleforge",
  "Snickerdash",
  "Velcrobeard",
  "Quasaroo",
  "Marmalade",
  "Thunderhat",
  "Gobbleton",
  "Zapleton",
  "Banjosmith",
  "Cosmobean",
  "Wobbleton",
  "Flipstick",
  "Noodleton",
  "Crumblepot",
  "Razzlefin",
  "Lemonbyte",
  "Frothwick",
  "Pebbleford",
  "Tinseltoe",
  "Gadgetson",
  "Wormwood",
  "Bananafax",
  "Picklebarrel",
  "Spindlepop",
  "Rockett",
  "Chimneyspark",
  "Frostpunch",
  "Echoquill",
  "Glimmerfox",
  "Scootles",
  "Pancake",
  "Thunderflip",
  "Wafflehorn",
  "Sporkle",
  "Muffin",
  "Zigzagger",
  "Taterchip",
  "Dandelion",
  "Snortle",
  "Velvetshoe",
  "Cosmicus",
  "Gobbler",
  "Zapwhirl",
  "Glimmergloop",
  "Bramblebat",
  "Suncrumb",
];

const pickRandom = (values: string[]) => {
  return values[Math.floor(Math.random() * values.length)];
};

export const createRandomAgentName = () => {
  return `${pickRandom(FIRST_NAMES)}-${pickRandom(LAST_NAMES)}`;
};

export const normalizeAgentName = (input: string) => {
  return input.trim().replace(/\s+/g, "-");
};
